language: java

sudo: false
cache:
  directories:
      - $HOME/.m2

dist: trusty

before_install:
  - grep -q -z '<artifactId>killbill-oss-parent</artifactId>[[:space:]]\+<groupId>org.kill-bill.billing</groupId>[[:space:]]\+<version>[0-9\.]*-SNAPSHOT</version>' pom.xml && echo "killbill-oss-parent SNAPSHOT has been found, exiting." && exit 0 || true
  - echo "<settings><profiles><profile><repositories><repository><id>central</id><name>bintray</name><url>http://jcenter.bintray.com</url></repository></repositories><id>bintray</id></profile></profiles><activeProfiles><activeProfile>bintray</activeProfile></activeProfiles></settings>" > /var/tmp/settings.xml

before_script:
  - jdk_switcher use $JDK
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && curl -s checkip.dyndns.org && printf "org.killbill.billing.plugin.adyen.merchantAccount=${ADYEN_MERCHANT_ACCOUNT}\\norg.killbill.billing.plugin.adyen.username=${ADYEN_USERNAME}\\norg.killbill.billing.plugin.adyen.password=${ADYEN_PASSWORD}\\norg.killbill.billing.plugin.adyen.paymentUrl=${ADYEN_PAYMENT_URL}\\norg.killbill.billing.plugin.adyen.recurringUrl=${ADYEN_RECURRING_URL}\\norg.killbill.billing.plugin.adyen.hmac.secret=${ADYEN_HMAC_SECRET}\\norg.killbill.billing.plugin.adyen.skin=${ADYEN_SKIN}\\norg.killbill.billing.plugin.adyen.hpp.target=${ADYEN_HPP_TARGET}\\norg.killbill.billing.plugin.adyen.directoryUrl=${ADYEN_DIRECTORY_URL}\\n" > src/test/resources/adyen.properties'
after_script: rm -f src/test/resources/adyen.properties
script: if [[ -v COMMAND ]]; then $COMMAND; else travis_retry mvn clean install $PHASE | egrep -v 'Download|Install'; [ ${PIPESTATUS[0]} == 0 ]; fi
# Remove --quiet to avoid timeouts
install: mvn -U install -DskipTests=true --settings /var/tmp/settings.xml | egrep -v 'Download|Install'

notifications:
  email:
    - kill-bill-commits@googlegroups.com

matrix:
  include:
    - env: PHASE="-Ptravis,jdk18" JDK=openjdk8
  fast_finish: true
