version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx2048m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: curl -s checkip.dyndns.org && printf "org.killbill.billing.plugin.adyen.merchantAccount=${ADYEN_MERCHANT_ACCOUNT}\\norg.killbill.billing.plugin.adyen.username=${ADYEN_USERNAME}\\norg.killbill.billing.plugin.adyen.password=${ADYEN_PASSWORD}\\norg.killbill.billing.plugin.adyen.paymentUrl=${ADYEN_PAYMENT_URL}\\norg.killbill.billing.plugin.adyen.recurringUrl=${ADYEN_RECURRING_URL}\\norg.killbill.billing.plugin.adyen.hmac.secret=${ADYEN_HMAC_SECRET}\\norg.killbill.billing.plugin.adyen.skin=${ADYEN_SKIN}\\norg.killbill.billing.plugin.adyen.hpp.target=${ADYEN_HPP_TARGET}\\norg.killbill.billing.plugin.adyen.directoryUrl=${ADYEN_DIRECTORY_URL}\\n" > src/test/resources/adyen.properties'

      # run tests!
      - run: mvn install -Ptravis

