version: 2
jobs:
  build:
    docker:
      - image: killbill/kbbuild:0.1.0

    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx2048m

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn -DskipTests=true clean install dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: curl -s checkip.dyndns.org && printf "org.killbill.billing.plugin.adyen.merchantAccount=${ADYEN_MERCHANT_ACCOUNT}\\norg.killbill.billing.plugin.adyen.username=${ADYEN_USERNAME}\\norg.killbill.billing.plugin.adyen.password=${ADYEN_PASSWORD}\\norg.killbill.billing.plugin.adyen.paymentUrl=${ADYEN_PAYMENT_URL}\\norg.killbill.billing.plugin.adyen.recurringUrl=${ADYEN_RECURRING_URL}\\norg.killbill.billing.plugin.adyen.hmac.secret=${ADYEN_HMAC_SECRET}\\norg.killbill.billing.plugin.adyen.skin=${ADYEN_SKIN}\\norg.killbill.billing.plugin.adyen.hpp.target=${ADYEN_HPP_TARGET}\\norg.killbill.billing.plugin.adyen.directoryUrl=${ADYEN_DIRECTORY_URL}\\n" > src/test/resources/adyen.properties

      # Run tests
      - run: mvn clean install -Ptravis

      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      - deploy:
          name: Maybe release
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              eval ${DO_RELEASE}
            fi
